Fix for tensorflow 2.20
When using python 3.13 and tensorflow 2.20 the slicing is used with
two different data types which results in the following type error:

TypeError: Input 'end' of 'StridedSlice' Op has type int16 that does not match type int32 of argument 'begin'.